export const endpoints = {
  LOGIN: 'login',
  TOKEN_REFRESH: 'token-refresh',
  CONTRACTOR: 'contractors',
  MANAGE_NEWS_PROJECTS: 'manage-news-projects',
  BURST_NEWS: 'burst-news',
  NEWS_PROJECTS: 'news-projects',
  HASHTAGS: 'hashtags',
  POST_FORMAT: 'post-format',
  USERS: 'users',
  CONFIRM_USER: 'confirm-user',
  INVITE_NEW_USER: 'invite-new-user',
  CHANGE_GROUP: 'change-group',
  CHANGE_PASSWORD_CONFIRM: 'change-password-confirm',
  CHANGE_PASS: 'change-pass',
  PROFILE: 'profile',
  POST_FORMATS: 'postformats',
  PROJECTS: 'projects',
  EMAILS: 'emails'
};
